SOURCE_DIR = "npy"
LABELS_FILE = "png/emotion.txt"

BATCH_DATA_SIZE = 15
CHANELLS = 1

WIDTH = 128
HEIGHT = 128
IMG_SHAPE = (HEIGHT, WIDTH)
IN_SHAPE = (None, HEIGHT, WIDTH, CHANELLS)

OUT_SIZE = 7
OUT_SHAPE = (OUT_SIZE)
