SOURCE_DIR = "npy"
LABELS_FILE = "png/emotion.txt"

BATCH_DATA_SIZE = 100
CHANNELS = 3

WIDTH = 128
HEIGHT = 128
IMG_SHAPE = (HEIGHT, WIDTH, CHANNELS)
IN_SHAPE = (None, HEIGHT, WIDTH, CHANNELS)

OUT_SIZE = 7
OUT_SHAPE = (OUT_SIZE)
