SOURCE_DIR = "npy"

META_FILE = "models/model.meta"
MODEL_FILE = "models/model"
CHECKPOINTS_FILE = "checkpoints/models"
LABELS_FILE = "png/emotion.txt"

CHANNELS = 3

WIDTH = 128
HEIGHT = 128
IMG_SHAPE = (HEIGHT, WIDTH, CHANNELS)
IN_SHAPE = (None, HEIGHT, WIDTH, CHANNELS)

CLASSES_NUM = 7
OUT_SHAPE = CLASSES_NUM